version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Fileflow-Backend
    networks:
      - internal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Fileflow-Frontend
    depends_on:
      - backend
    networks:
      - internal-network

  nginx:
    image: nginx:latest
    container_name: Fileflow-Nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
